# Generated by Django 4.2.4 on 2023-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='gallery/istockphoto-1224991426-612x612.jpg', upload_to='gallery'),
        ),
    ]
