# Generated by Django 4.2.3 on 2023-08-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_sold_product_owner_alter_sold_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_product',
            name='owner',
        ),
    ]
