# Generated by Django 4.2.3 on 2023-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
