# Generated by Django 4.2.3 on 2023-08-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_sold_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
