# Generated by Django 4.2.3 on 2023-08-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_sold_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
