# Generated by Django 4.2.3 on 2023-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_sold_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sold_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
