# Generated by Django 4.2.3 on 2023-08-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_sold_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_product',
            name='price',
        ),
    ]
