# Generated by Django 4.2.3 on 2023-08-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_remove_sold_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_product',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
