# Generated by Django 4.2.3 on 2023-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_product_price_alter_sold_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_product',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
