# Generated by Django 4.2.3 on 2023-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_sold_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
